export const allProducts = [
  // BOUQUET
  { id: 3,  name: "Red Bouquet",              subtitle: "Classic Romance",       price: 120, category: "Bouquet",    slug: "bouquet",    img: "/static/images/products/red-bouquet.jpg",              description: "A stunning red bouquet that speaks the language of love. Crafted with deep red blooms, this arrangement is ideal for romantic occasions, Valentine's Day, or as a heartfelt gift for someone special." },
  { id: 4,  name: "Peach Bouquet",            subtitle: "Soft & Elegant",        price: 110, category: "Bouquet",    slug: "bouquet",    img: "/static/images/products/peach-bouquet.jpg",            description: "Soft peach tones make this bouquet a symbol of warmth and sincerity. Delicately arranged with pastel blooms, it's perfect for weddings, baby showers, or as a gentle gesture of appreciation." },
  { id: 6,  name: "White Bouquet",            subtitle: "Pure & Graceful",       price: 130, category: "Bouquet",    slug: "bouquet",    img: "/static/images/products/white-bouquet.jpg",            description: "Elegant and timeless, this white bouquet radiates purity and grace. Ideal for weddings, christenings, or any formal occasion. Each bloom is hand-selected for its pristine beauty and freshness." },
  { id: 7,  name: "Blue Bouquet",             subtitle: "Cool & Calming",        price: 115, category: "Bouquet",    slug: "bouquet",    img: "/static/images/products/blue-bouquet.jpg",             description: "A unique and calming blue bouquet that stands out from the rest. Perfect for those who love something different — a thoughtful gift that brings a sense of peace and tranquility to any space." },
  { id: 20, name: "Forever Petals Bouquet",   subtitle: "Timeless & Beautiful",  price: 145, category: "Bouquet",    slug: "bouquet",    img: "/static/images/products/forever-petals-bouquet.png",  description: "A forever-lasting felt bouquet that never wilts. Handcrafted petal by petal, this timeless arrangement is a keepsake gift that will be cherished for years. No watering needed — just pure beauty." },
  { id: 22, name: "Pink Lily Felt Bouquet",   subtitle: "Soft & Lovely",         price: 135, category: "Bouquet",    slug: "bouquet",    img: "/static/images/products/pink-lily-felt-bouquet.png",  description: "A charming felt bouquet featuring soft pink lilies. Handmade with premium felt fabric, this bouquet is a long-lasting alternative to fresh flowers. Great as a room decoration or a unique gift." },
  { id: 24, name: "Pink Bouquet",             subtitle: "Sweet & Romantic",      price: 105, category: "Bouquet",    slug: "bouquet",    img: "/static/images/products/pink-bouquet.jpg",             description: "Sweet and romantic, this pink bouquet is perfect for expressing affection. Filled with soft pink blooms, it's a wonderful gift for Mother's Day, birthdays, or any day you want to make someone smile." },
  { id: 27, name: "Black & Red Lily Bouquet", subtitle: "Bold & Romantic",       price: 150, category: "Bouquet",    slug: "bouquet",    img: "/static/images/products/black-red-lily-bouquet.png",  description: "A bold and dramatic bouquet combining deep red lilies with dark accents. This striking arrangement makes a powerful statement and is perfect for those who love a touch of drama and elegance." },
  { id: 26, name: "Yellow Lily Bouquet",      subtitle: "Bright & Cheerful",     price: 140, category: "Bouquet",    slug: "bouquet",    img: "/static/images/products/yellow-lily-bouquet.jpg",     description: "Bright and cheerful yellow lilies arranged in a beautiful bouquet. This sunny arrangement is perfect for congratulations, get-well wishes, or simply spreading joy and positivity to someone you care about." },

  // FLOWER POT
  { id: 8,  name: "Flower Pot",               subtitle: "Botanical Bliss",       price: 150, category: "Flower Pot", slug: "flower-pot", img: "/static/images/products/flower-pot.jpg",              description: "A beautifully arranged flower pot that brings nature indoors. Perfect for home or office decoration, this botanical piece adds a fresh and lively touch to any space. Low maintenance and long-lasting." },
  { id: 17, name: "Chenipot Daisy",           subtitle: "Bright & Blooming",     price: 160, category: "Flower Pot", slug: "flower-pot", img: "/static/images/products/chenipot-daisy.png",          description: "A cheerful Chenipot featuring handcrafted daisy blooms. Each petal is carefully shaped and arranged in a charming pot. A delightful decoration piece that brightens any room with its playful design." },
  { id: 18, name: "Chenipot Lily",            subtitle: "Elegant & Fragrant",    price: 175, category: "Flower Pot", slug: "flower-pot", img: "/static/images/products/chenipot-lily.png",           description: "An elegant Chenipot featuring graceful lily blooms. Handcrafted with attention to detail, this piece combines artistry and nature. A sophisticated decoration for living rooms, offices, or as a premium gift." },
  { id: 19, name: "Chenipot Small Daisies",   subtitle: "Cute & Petite",         price: 140, category: "Flower Pot", slug: "flower-pot", img: "/static/images/products/chenipot-small-daisies.png",  description: "Adorable small daisies arranged in a cute Chenipot. This petite decoration piece is perfect for desks, shelves, or windowsills. A sweet and charming gift for anyone who loves flowers." },
  { id: 21, name: "Chenipot Lotus",           subtitle: "Serene & Graceful",     price: 180, category: "Flower Pot", slug: "flower-pot", img: "/static/images/products/chenipot-lotus.png",          description: "A serene Chenipot featuring a handcrafted lotus bloom. The lotus symbolizes purity and enlightenment, making this a meaningful and beautiful gift. Perfect for meditation spaces or as a zen-inspired decoration." },
  { id: 23, name: "Tulips",                   subtitle: "Fresh & Vibrant",       price: 125, category: "Flower Pot", slug: "flower-pot", img: "/static/images/products/tulips.png",                  description: "Vibrant handcrafted tulips arranged in a charming pot. These colorful blooms bring the beauty of spring indoors all year round. A cheerful and eye-catching decoration for any home or office space." },

  // KEYCHAIN
  { id: 15, name: "Fuzz Mirror",              subtitle: "Fluffy & Unique",       price: 200, category: "Keychain",   slug: "keychain",   img: "/static/images/products/fuzz-mirror.jpg",             description: "A unique and fluffy mirror keychain that doubles as a cute accessory. Handcrafted with soft fuzz material, this one-of-a-kind piece is both functional and fashionable. Perfect as a bag charm or gift." },
  { id: 28, name: "Strawberry Keychain",      subtitle: "Sweet & Playful",       price: 95,  category: "Keychain",   slug: "keychain",   img: "/static/images/products/strawberry-keychain.jpg",     description: "A sweet and playful strawberry keychain handcrafted with love. This adorable accessory adds a fun touch to your keys or bag. A perfect gift for anyone who loves cute and quirky accessories." },
  { id: 29, name: "Cute Animal Keychain",     subtitle: "Adorable & Fun",        price: 90,  category: "Keychain",   slug: "keychain",   img: "/static/images/products/cute-animal-keychain.png",    description: "An adorable handcrafted animal keychain that's sure to bring a smile. Made with premium materials, this cute accessory is perfect for kids and adults alike. A charming gift for animal lovers." },
  { id: 30, name: "Cherry Keychain",          subtitle: "Bright & Charming",     price: 92,  category: "Keychain",   slug: "keychain",   img: "/static/images/products/cherry-keychain.png",         description: "A bright and charming cherry keychain handcrafted with vibrant colors. This eye-catching accessory is perfect for adding a pop of color to your keys or bag. A sweet gift for anyone who loves cute things." },
  { id: 31, name: "Roll Cake Keychain",       subtitle: "Sweet & Cozy",          price: 94,  category: "Keychain",   slug: "keychain",   img: "/static/images/products/roll-cake-keychain.png",      description: "A delightfully sweet roll cake keychain that looks good enough to eat! Handcrafted with soft materials, this cozy accessory is a unique and charming gift for food lovers and keychain collectors." },
  { id: 32, name: "Sushi Keychain",           subtitle: "Cute & Quirky",         price: 96,  category: "Keychain",   slug: "keychain",   img: "/static/images/products/sushi-keychain.png",          description: "A cute and quirky sushi keychain that's a conversation starter. Handcrafted with fun details, this unique accessory is perfect for sushi lovers or anyone who appreciates creative and playful designs." },
];
